SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rnk
    FROM REST_INFO
) t
WHERE rnk = 1
ORDER BY FOOD_TYPE DESC;